package main

import (
	"github.com/invopop/jsonschema"
	"github.com/spf13/cobra"

	"github.com/steveyegge/beads/internal/types"
)

// schemaCmd emits the JSON Schema for bd's canonical --json / export output
// record types.
//
// The schema is generated by reflection from the same internal/types structs
// that bd serializes, so by construction it cannot drift from the actual output
// the way a hand-maintained doc (docs/JSON_SCHEMA.md) or a downstream consumer
// model (e.g. beads-mcp's Pydantic models) can. The emitted schema_version
// matches JSONSchemaVersion and bumps with it.
//
// Consumers can codegen typed models from this output (datamodel-code-generator
// for Python/Pydantic, quicktype, etc.) instead of hand-mirroring the format.
var schemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Print the JSON Schema for bd's --json / export output",
	Long: `Print the JSON Schema for bd's canonical output record types.

The schema is reflected from the same Go structs bd serializes, so it stays in
lockstep with the actual --json / export output. Use it to generate typed
consumer models (datamodel-code-generator, quicktype, ...) rather than
hand-maintaining them.

  bd schema | jq '.types.issue'        # the issue record schema
  bd schema | jq '.types.dependency'   # the dependency record schema`,
	Run: func(cmd *cobra.Command, args []string) {
		// Inline referenced types so each record schema is self-contained and
		// directly consumable by codegen tools.
		reflector := &jsonschema.Reflector{DoNotReference: true}

		doc := map[string]interface{}{
			"schema_version": JSONSchemaVersion,
			"types": map[string]*jsonschema.Schema{
				"issue":      reflector.Reflect(&types.Issue{}),
				"dependency": reflector.Reflect(&types.Dependency{}),
			},
		}
		// Raw: the document carries its own schema_version; do not double-wrap
		// it in the --json envelope.
		outputJSONRaw(doc)
	},
}

func init() {
	rootCmd.AddCommand(schemaCmd)
}
